version: '3.8'

services:
  db:
    image: postgres:13
    container_name: ncd_db
    environment:
      POSTGRES_USER: flaws_sins
      POSTGRES_PASSWORD: QuantumSuperposition
      POSTGRES_DB: ncd_database
    ports:
      - "5433:5432"  # mapped to 5433 to avoid host conflict
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ncd_api
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: wsgi.py
      DATABASE_URI: postgresql://flaws_sins:QuantumSuperposition@db:5432/ncd_database
      SECRET_KEY: super-secret-key
      JWT_SECRET_KEY: another-super-secret-key
    depends_on:
      - db
    command: >
      sh -c "flask db upgrade &&
             python seed.py &&
             gunicorn --worker-tmp-dir /dev/shm wsgi:app"
    restart: always

volumes:
  postgres_data:
